version: '2'
services:
  odoo9:
    image: odoo:9
    environment:
        PGHOST: db
        PGUSER: odoo
        PGPASSWORD: odoo
    tty: true
    ports:
      - 8069:8069
    volumes:
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    links:
      - db:db
    depends_on:
      - db
  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
